
// Module order in this file:
//   1. AES128_updated_new : top module and main finite state machine (FSM)
//   2. AES_SBOX_ROM       : AES S-box lookup table
//   3. AES_SBOX_SEQ       : sequential SubBytes engine
//   4. AES_MIXCOL_SEQ     : sequential MixColumns engine
//   5. AES_KEYEXP_SEQ     : AES-128 key expansion engine
//
// Design idea:
//   AES normally performs ten encryption rounds.  A fully parallel design may
//   instantiate many round blocks at the same time.  This design instead reuses
//   one set of hardware blocks under FSM control.  Reuse lowers area and reduces
//   simultaneous switching activity, which is useful for low-power FPGA/IoT
//   applications.
//
// Handshake:
//   - Apply plaintext and key.
//   - Pulse start high for one clock.
//   - The core asserts busy while encryption is running.
//   - When done becomes high, ciphertext is valid.
//
// Notes:
//   - <= is nonblocking assignment, used inside clocked always blocks.
//   - = is blocking assignment, used inside combinational functions/logic.
//   - [127 - (idx * 8) -: 8] means "select 8 bits starting from bit
//     127-(idx*8) and counting downward".
//   - Attributes such as keep/preserve help FPGA tools retain useful signal
//     names for debugging and RTL/netlist viewing. They do not change the AES
//     algorithm.
// -----------------------------------------------------------------------------


// =============================================================================
// Source: rtl/00_aes128_top.sv
// =============================================================================

// -----------------------------------------------------------------------------
// Top-level AES-128 sequential encryption core.
// File order starts here so readers see the external interface and FSM first.
// -----------------------------------------------------------------------------

module AES128_updated_new (
    input  wire         clk,
    input  wire         reset,
    input  wire         start,
    output reg          busy,
    output reg          done,
    input  wire [127:0] plaintext,
    input  wire [127:0] key,
    output reg  [127:0] ciphertext
);

// FSM state encoding.  The controller moves through these states to activate
// only the required AES block at each stage of the encryption flow.
localparam S_IDLE       = 4'd0;
localparam S_SUB_START  = 4'd1;
localparam S_SUB_WAIT   = 4'd2;
localparam S_MIX_START  = 4'd3;
localparam S_MIX_WAIT   = 4'd4;
localparam S_KEY_START  = 4'd5;
localparam S_KEY_WAIT   = 4'd6;
localparam S_DONE       = 4'd7;

// state      : current FSM state.
// state_reg  : 128-bit AES state being transformed round by round.
// round_key  : current 128-bit AES round key.
// round      : AES round counter, 1 through 10.
(* preserve = 1 *) reg [3:0]   state;
(* preserve = 1 *) reg [127:0] state_reg;
(* preserve = 1 *) reg [127:0] round_key;
(* preserve = 1 *) reg [3:0]   round;

// Outputs from the reusable AES sub-blocks.
wire [127:0] sb_out;
wire [127:0] mix_out;
wire [127:0] new_key;

// Done pulses from the reusable AES sub-blocks.
wire         sbox_done;
wire         mix_done;
wire         key_done;

// Start pulses generated by the top FSM.  Each pulse lasts one clock.
reg sbox_start;
reg mix_start;
reg key_start;

// AES state is stored as four 32-bit columns: b0..b3, b4..b7, b8..b11, b12..b15.
// ShiftRows rotates row 1 by 1 byte, row 2 by 2 bytes, and row 3 by 3 bytes.
function [127:0] shift_rows;
    input [127:0] s;
    reg [7:0] b0;  reg [7:0] b1;  reg [7:0] b2;  reg [7:0] b3;
    reg [7:0] b4;  reg [7:0] b5;  reg [7:0] b6;  reg [7:0] b7;
    reg [7:0] b8;  reg [7:0] b9;  reg [7:0] b10; reg [7:0] b11;
    reg [7:0] b12; reg [7:0] b13; reg [7:0] b14; reg [7:0] b15;
    begin
        {b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15} = s;
        shift_rows = {b0, b5, b10, b15, b4, b9, b14, b3, b8, b13, b2, b7, b12, b1, b6, b11};
    end
endfunction

// Helpful named datapath signals.  These make the RTL easier to read and make
// simulator/waveform names more meaningful.
(* keep = 1 *) wire [127:0] initial_addroundkey;
(* keep = 1 *) wire [127:0] state_after_shiftrows;
(* keep = 1 *) wire [127:0] state_after_roundkey;
(* keep = 1 *) wire         final_round;

assign initial_addroundkey  = plaintext ^ key;
assign state_after_shiftrows = shift_rows(sb_out);
assign state_after_roundkey = state_reg ^ new_key;
assign final_round          = (round == 4'd10);

// Reusable hardware blocks.
// u_sbox performs SubBytes one byte at a time.
// u_mix performs MixColumns one column at a time.
// u_key computes the next AES round key.
AES_SBOX_SEQ   u_sbox (.clk(clk), .reset(reset), .start(sbox_start), .in_block(state_reg), .out_block(sb_out),  .done(sbox_done));
AES_MIXCOL_SEQ u_mix  (.clk(clk), .reset(reset), .start(mix_start),  .in_block(state_reg), .out_block(mix_out), .done(mix_done));
AES_KEYEXP_SEQ u_key  (.clk(clk), .reset(reset), .start(key_start),  .round(round), .in_key(round_key), .out_key(new_key), .done(key_done));

always @(posedge clk or posedge reset) begin
    if (reset) begin
        // Asynchronous reset places the core in an idle, known state.
        state       <= S_IDLE;
        busy        <= 1'b0;
        done        <= 1'b0;
        round       <= 4'd1;
        state_reg   <= 128'd0;
        round_key   <= 128'd0;
        ciphertext  <= 128'd0;
        sbox_start  <= 1'b0;
        mix_start   <= 1'b0;
        key_start   <= 1'b0;
    end else begin
        // Starts are one-cycle pulses unless a state below asserts one.
        sbox_start <= 1'b0;
        mix_start  <= 1'b0;
        key_start  <= 1'b0;

        case (state)
            S_IDLE: begin
                // Wait here until the user pulses start.
                // The initial AES operation is AddRoundKey: plaintext XOR key.
                busy <= 1'b0;
                done <= 1'b0;
                if (start) begin
                    state_reg <= initial_addroundkey;
                    round_key <= key;
                    round     <= 4'd1;
                    busy      <= 1'b1;
                    state     <= S_SUB_START;
                end
            end

            S_SUB_START: begin
                // Ask the sequential SubBytes block to start processing the
                // 128-bit state. It will substitute one byte per clock.
                sbox_start <= 1'b1;
                state      <= S_SUB_WAIT;
            end

            S_SUB_WAIT: begin
                // Stay here until all 16 bytes have been substituted.
                // After SubBytes, ShiftRows is applied as a combinational
                // helper function. Rounds 1-9 go to MixColumns. Round 10 skips
                // MixColumns according to the AES specification.
                if (sbox_done) begin
                    state_reg <= state_after_shiftrows;
                    state     <= S_KEY_START;
                    if (!final_round) begin
                        state <= S_MIX_START;
                    end
                end
            end

            S_MIX_START: begin
                // Ask the sequential MixColumns block to start processing.
                // It processes one 32-bit AES column per clock.
                mix_start <= 1'b1;
                state     <= S_MIX_WAIT;
            end

            S_MIX_WAIT: begin
                // Wait until all four AES columns have been mixed.
                if (mix_done) begin
                    state_reg <= mix_out;
                    state     <= S_KEY_START;
                end
            end

            S_KEY_START: begin
                // Start AES-128 round-key expansion for the current round.
                key_start <= 1'b1;
                state     <= S_KEY_WAIT;
            end

            S_KEY_WAIT: begin
                // When the new round key is ready, perform AddRoundKey.
                // If this is the final round, register ciphertext and finish.
                // Otherwise, increment the round counter and repeat.
                if (key_done) begin
                    round_key <= new_key;
                    state_reg <= state_after_roundkey;

                    if (final_round) begin
                        ciphertext <= state_after_roundkey;
                        state      <= S_DONE;
                    end else begin
                        round <= round + 4'd1;
                        state <= S_SUB_START;
                    end
                end
            end

            S_DONE: begin
                // One-clock completion pulse. The ciphertext output is valid
                // when done is high.
                done  <= 1'b1;
                busy  <= 1'b0;
                state <= S_IDLE;
            end

            default: begin
                state <= S_IDLE;
            end
        endcase
    end
end
endmodule

// =============================================================================
// Source: rtl/01_aes_sbox_rom.sv
// =============================================================================

// -----------------------------------------------------------------------------
// AES S-box lookup ROM used by SubBytes and key expansion.
// -----------------------------------------------------------------------------

module AES_SBOX_ROM (
    input  wire [7:0] a,
    output reg  [7:0] c
);

// AES substitution box lookup table.
//
// The S-box is a fixed 256-entry table from the AES standard.  It maps one
// input byte to one output byte and provides the nonlinear "confusion" step in
// AES.  This implementation is combinational: whenever input a changes, output
// c changes immediately after combinational delay.
always @(*) begin
    case (a)
        8'h00: c = 8'h63; 8'h01: c = 8'h7c; 8'h02: c = 8'h77; 8'h03: c = 8'h7b;
        8'h04: c = 8'hf2; 8'h05: c = 8'h6b; 8'h06: c = 8'h6f; 8'h07: c = 8'hc5;
        8'h08: c = 8'h30; 8'h09: c = 8'h01; 8'h0a: c = 8'h67; 8'h0b: c = 8'h2b;
        8'h0c: c = 8'hfe; 8'h0d: c = 8'hd7; 8'h0e: c = 8'hab; 8'h0f: c = 8'h76;
        8'h10: c = 8'hca; 8'h11: c = 8'h82; 8'h12: c = 8'hc9; 8'h13: c = 8'h7d;
        8'h14: c = 8'hfa; 8'h15: c = 8'h59; 8'h16: c = 8'h47; 8'h17: c = 8'hf0;
        8'h18: c = 8'had; 8'h19: c = 8'hd4; 8'h1a: c = 8'ha2; 8'h1b: c = 8'haf;
        8'h1c: c = 8'h9c; 8'h1d: c = 8'ha4; 8'h1e: c = 8'h72; 8'h1f: c = 8'hc0;
        8'h20: c = 8'hb7; 8'h21: c = 8'hfd; 8'h22: c = 8'h93; 8'h23: c = 8'h26;
        8'h24: c = 8'h36; 8'h25: c = 8'h3f; 8'h26: c = 8'hf7; 8'h27: c = 8'hcc;
        8'h28: c = 8'h34; 8'h29: c = 8'ha5; 8'h2a: c = 8'he5; 8'h2b: c = 8'hf1;
        8'h2c: c = 8'h71; 8'h2d: c = 8'hd8; 8'h2e: c = 8'h31; 8'h2f: c = 8'h15;
        8'h30: c = 8'h04; 8'h31: c = 8'hc7; 8'h32: c = 8'h23; 8'h33: c = 8'hc3;
        8'h34: c = 8'h18; 8'h35: c = 8'h96; 8'h36: c = 8'h05; 8'h37: c = 8'h9a;
        8'h38: c = 8'h07; 8'h39: c = 8'h12; 8'h3a: c = 8'h80; 8'h3b: c = 8'he2;
        8'h3c: c = 8'heb; 8'h3d: c = 8'h27; 8'h3e: c = 8'hb2; 8'h3f: c = 8'h75;
        8'h40: c = 8'h09; 8'h41: c = 8'h83; 8'h42: c = 8'h2c; 8'h43: c = 8'h1a;
        8'h44: c = 8'h1b; 8'h45: c = 8'h6e; 8'h46: c = 8'h5a; 8'h47: c = 8'ha0;
        8'h48: c = 8'h52; 8'h49: c = 8'h3b; 8'h4a: c = 8'hd6; 8'h4b: c = 8'hb3;
        8'h4c: c = 8'h29; 8'h4d: c = 8'he3; 8'h4e: c = 8'h2f; 8'h4f: c = 8'h84;
        8'h50: c = 8'h53; 8'h51: c = 8'hd1; 8'h52: c = 8'h00; 8'h53: c = 8'hed;
        8'h54: c = 8'h20; 8'h55: c = 8'hfc; 8'h56: c = 8'hb1; 8'h57: c = 8'h5b;
        8'h58: c = 8'h6a; 8'h59: c = 8'hcb; 8'h5a: c = 8'hbe; 8'h5b: c = 8'h39;
        8'h5c: c = 8'h4a; 8'h5d: c = 8'h4c; 8'h5e: c = 8'h58; 8'h5f: c = 8'hcf;
        8'h60: c = 8'hd0; 8'h61: c = 8'hef; 8'h62: c = 8'haa; 8'h63: c = 8'hfb;
        8'h64: c = 8'h43; 8'h65: c = 8'h4d; 8'h66: c = 8'h33; 8'h67: c = 8'h85;
        8'h68: c = 8'h45; 8'h69: c = 8'hf9; 8'h6a: c = 8'h02; 8'h6b: c = 8'h7f;
        8'h6c: c = 8'h50; 8'h6d: c = 8'h3c; 8'h6e: c = 8'h9f; 8'h6f: c = 8'ha8;
        8'h70: c = 8'h51; 8'h71: c = 8'ha3; 8'h72: c = 8'h40; 8'h73: c = 8'h8f;
        8'h74: c = 8'h92; 8'h75: c = 8'h9d; 8'h76: c = 8'h38; 8'h77: c = 8'hf5;
        8'h78: c = 8'hbc; 8'h79: c = 8'hb6; 8'h7a: c = 8'hda; 8'h7b: c = 8'h21;
        8'h7c: c = 8'h10; 8'h7d: c = 8'hff; 8'h7e: c = 8'hf3; 8'h7f: c = 8'hd2;
        8'h80: c = 8'hcd; 8'h81: c = 8'h0c; 8'h82: c = 8'h13; 8'h83: c = 8'hec;
        8'h84: c = 8'h5f; 8'h85: c = 8'h97; 8'h86: c = 8'h44; 8'h87: c = 8'h17;
        8'h88: c = 8'hc4; 8'h89: c = 8'ha7; 8'h8a: c = 8'h7e; 8'h8b: c = 8'h3d;
        8'h8c: c = 8'h64; 8'h8d: c = 8'h5d; 8'h8e: c = 8'h19; 8'h8f: c = 8'h73;
        8'h90: c = 8'h60; 8'h91: c = 8'h81; 8'h92: c = 8'h4f; 8'h93: c = 8'hdc;
        8'h94: c = 8'h22; 8'h95: c = 8'h2a; 8'h96: c = 8'h90; 8'h97: c = 8'h88;
        8'h98: c = 8'h46; 8'h99: c = 8'hee; 8'h9a: c = 8'hb8; 8'h9b: c = 8'h14;
        8'h9c: c = 8'hde; 8'h9d: c = 8'h5e; 8'h9e: c = 8'h0b; 8'h9f: c = 8'hdb;
        8'ha0: c = 8'he0; 8'ha1: c = 8'h32; 8'ha2: c = 8'h3a; 8'ha3: c = 8'h0a;
        8'ha4: c = 8'h49; 8'ha5: c = 8'h06; 8'ha6: c = 8'h24; 8'ha7: c = 8'h5c;
        8'ha8: c = 8'hc2; 8'ha9: c = 8'hd3; 8'haa: c = 8'hac; 8'hab: c = 8'h62;
        8'hac: c = 8'h91; 8'had: c = 8'h95; 8'hae: c = 8'he4; 8'haf: c = 8'h79;
        8'hb0: c = 8'he7; 8'hb1: c = 8'hc8; 8'hb2: c = 8'h37; 8'hb3: c = 8'h6d;
        8'hb4: c = 8'h8d; 8'hb5: c = 8'hd5; 8'hb6: c = 8'h4e; 8'hb7: c = 8'ha9;
        8'hb8: c = 8'h6c; 8'hb9: c = 8'h56; 8'hba: c = 8'hf4; 8'hbb: c = 8'hea;
        8'hbc: c = 8'h65; 8'hbd: c = 8'h7a; 8'hbe: c = 8'hae; 8'hbf: c = 8'h08;
        8'hc0: c = 8'hba; 8'hc1: c = 8'h78; 8'hc2: c = 8'h25; 8'hc3: c = 8'h2e;
        8'hc4: c = 8'h1c; 8'hc5: c = 8'ha6; 8'hc6: c = 8'hb4; 8'hc7: c = 8'hc6;
        8'hc8: c = 8'he8; 8'hc9: c = 8'hdd; 8'hca: c = 8'h74; 8'hcb: c = 8'h1f;
        8'hcc: c = 8'h4b; 8'hcd: c = 8'hbd; 8'hce: c = 8'h8b; 8'hcf: c = 8'h8a;
        8'hd0: c = 8'h70; 8'hd1: c = 8'h3e; 8'hd2: c = 8'hb5; 8'hd3: c = 8'h66;
        8'hd4: c = 8'h48; 8'hd5: c = 8'h03; 8'hd6: c = 8'hf6; 8'hd7: c = 8'h0e;
        8'hd8: c = 8'h61; 8'hd9: c = 8'h35; 8'hda: c = 8'h57; 8'hdb: c = 8'hb9;
        8'hdc: c = 8'h86; 8'hdd: c = 8'hc1; 8'hde: c = 8'h1d; 8'hdf: c = 8'h9e;
        8'he0: c = 8'he1; 8'he1: c = 8'hf8; 8'he2: c = 8'h98; 8'he3: c = 8'h11;
        8'he4: c = 8'h69; 8'he5: c = 8'hd9; 8'he6: c = 8'h8e; 8'he7: c = 8'h94;
        8'he8: c = 8'h9b; 8'he9: c = 8'h1e; 8'hea: c = 8'h87; 8'heb: c = 8'he9;
        8'hec: c = 8'hce; 8'hed: c = 8'h55; 8'hee: c = 8'h28; 8'hef: c = 8'hdf;
        8'hf0: c = 8'h8c; 8'hf1: c = 8'ha1; 8'hf2: c = 8'h89; 8'hf3: c = 8'h0d;
        8'hf4: c = 8'hbf; 8'hf5: c = 8'he6; 8'hf6: c = 8'h42; 8'hf7: c = 8'h68;
        8'hf8: c = 8'h41; 8'hf9: c = 8'h99; 8'hfa: c = 8'h2d; 8'hfb: c = 8'h0f;
        8'hfc: c = 8'hb0; 8'hfd: c = 8'h54; 8'hfe: c = 8'hbb; 8'hff: c = 8'h16;
        default: c = 8'h00;
    endcase
end
endmodule

// =============================================================================
// Source: rtl/02_aes_sbox_seq.sv
// =============================================================================

// -----------------------------------------------------------------------------
// Sequential SubBytes block: substitutes one byte per clock for 16 clocks.
// -----------------------------------------------------------------------------

module AES_SBOX_SEQ (
    input  wire         clk,
    input  wire         reset,
    input  wire         start,
    input  wire [127:0] in_block,
    output reg  [127:0] out_block,
    output reg          done
);

// running is high while the module is substituting bytes.
// idx selects which byte of the 128-bit input block is currently being read.
(* preserve = 1 *) reg        running;
(* preserve = 1 *) reg [3:0]  idx;

// s_in is the current byte sent into the S-box.
// s_out is the substituted byte returned from the S-box.
(* keep = 1 *) wire [7:0] s_in;
wire [7:0] s_out;

// One S-box ROM is reused for all 16 bytes.  This saves hardware compared to
// using 16 S-boxes in parallel, at the cost of extra clock cycles.
AES_SBOX_ROM rom (.a(s_in), .c(s_out));

// Select one byte per clock from MSB to LSB.
assign s_in = in_block[127 - (idx * 8) -: 8];

always @(posedge clk or posedge reset) begin
    if (reset) begin
        idx       <= 4'd0;
        done      <= 1'b0;
        running   <= 1'b0;
        out_block <= 128'd0;
    end else begin
        done <= 1'b0;

        if (start && !running) begin
            // Begin a new 16-byte substitution pass.
            idx     <= 4'd0;
            running <= 1'b1;
        end else if (running) begin
            // Store the substituted byte back into the same byte position.
            out_block[127 - (idx * 8) -: 8] <= s_out;

            if (idx == 4'd15) begin
                // Last byte has been written.  Raise done for one clock.
                running <= 1'b0;
                done    <= 1'b1;
            end else begin
                idx <= idx + 4'd1;
            end
        end
    end
end
endmodule

// =============================================================================
// Source: rtl/03_aes_mix_columns_seq.sv
// =============================================================================

// -----------------------------------------------------------------------------
// Sequential MixColumns block: processes one 32-bit AES column per clock.
// -----------------------------------------------------------------------------

module AES_MIXCOL_SEQ (
    input  wire         clk,
    input  wire         reset,
    input  wire         start,
    input  wire [127:0] in_block,
    output reg  [127:0] out_block,
    output reg          done
);

// running is high while the module is processing columns.
// col selects one of the four 32-bit AES state columns.
(* preserve = 1 *) reg        running;
(* preserve = 1 *) reg [1:0]  col;

// word is the selected input column.
// mc is the MixColumns result for that selected column.
(* keep = 1 *) reg [31:0] word;
(* keep = 1 *) reg [31:0] mc;

// Multiply by x in GF(2^8), reduced by AES polynomial x^8+x^4+x^3+x+1.
function [7:0] xt;
    input [7:0] b;
    begin
        xt = {b[6:0], 1'b0} ^ (8'h1b & {8{b[7]}});
    end
endfunction

// Computes one MixColumns output byte: 2*a + 3*b + c + d.
function [7:0] mixb;
    input [7:0] a;
    input [7:0] b;
    input [7:0] c;
    input [7:0] d;
    begin
        mixb = xt(a) ^ (xt(b) ^ b) ^ c ^ d;
    end
endfunction

always @(*) begin
    // Pick one 32-bit column from the 128-bit AES state.
    case (col)
        2'd0: word = in_block[127:96];
        2'd1: word = in_block[95:64];
        2'd2: word = in_block[63:32];
        2'd3: word = in_block[31:0];
    endcase

    // Compute the four output bytes for this column.  AES MixColumns is a fixed
    // matrix multiplication over GF(2^8).  The mixb helper computes one row of
    // that matrix.
    mc = {
        mixb(word[31:24], word[23:16], word[15:8],  word[7:0]),
        mixb(word[23:16], word[15:8],  word[7:0],   word[31:24]),
        mixb(word[15:8],  word[7:0],   word[31:24], word[23:16]),
        mixb(word[7:0],   word[31:24], word[23:16], word[15:8])
    };
end

always @(posedge clk or posedge reset) begin
    if (reset) begin
        running   <= 1'b0;
        col       <= 2'd0;
        done      <= 1'b0;
        out_block <= 128'd0;
    end else begin
        done <= 1'b0;

        if (start && !running) begin
            // Begin processing column 0.
            running <= 1'b1;
            col     <= 2'd0;
        end else if (running) begin
            // Write the mixed column into its matching position.
            out_block[127 - (col * 32) -: 32] <= mc;

            if (col == 2'd3) begin
                // All four columns are complete.  Raise done for one clock.
                running <= 1'b0;
                done    <= 1'b1;
            end else begin
                col <= col + 2'd1;
            end
        end
    end
end
endmodule

// =============================================================================
// Source: rtl/04_aes_key_expand_seq.sv
// =============================================================================

// -----------------------------------------------------------------------------
// AES-128 round-key expansion block.
// -----------------------------------------------------------------------------

module AES_KEYEXP_SEQ (
    input  wire         clk,
    input  wire         reset,
    input  wire         start,
    input  wire [3:0]   round,
    input  wire [127:0] in_key,
    output reg  [127:0] out_key,
    output reg          done
);

// This block computes the next 128-bit AES round key from the current key.
// It is sequential from the top-level point of view: start begins the operation
// and done pulses when out_key has been registered.
(* preserve = 1 *) reg        running;
wire [7:0] b0;
wire [7:0] b1;
wire [7:0] b2;
wire [7:0] b3;
(* keep = 1 *) reg [31:0] temp;

// RotWord followed by SubWord on the previous key's last word.
// AES key expansion takes the last 32-bit word, rotates it, substitutes each
// byte using the S-box, XORs the round constant, and then builds the next four
// key words using XOR chains.
AES_SBOX_ROM s0 (.a(in_key[23:16]), .c(b0));
AES_SBOX_ROM s1 (.a(in_key[15:8]),  .c(b1));
AES_SBOX_ROM s2 (.a(in_key[7:0]),   .c(b2));
AES_SBOX_ROM s3 (.a(in_key[31:24]), .c(b3));

function [31:0] RCON;
    input [3:0] r;
    begin
        case (r)
            4'd1:  RCON = 32'h01000000;
            4'd2:  RCON = 32'h02000000;
            4'd3:  RCON = 32'h04000000;
            4'd4:  RCON = 32'h08000000;
            4'd5:  RCON = 32'h10000000;
            4'd6:  RCON = 32'h20000000;
            4'd7:  RCON = 32'h40000000;
            4'd8:  RCON = 32'h80000000;
            4'd9:  RCON = 32'h1b000000;
            4'd10: RCON = 32'h36000000;
            default: RCON = 32'h00000000;
        endcase
    end
endfunction

always @(posedge clk or posedge reset) begin
    if (reset) begin
        running <= 1'b0;
        done    <= 1'b0;
        out_key <= 128'd0;
    end else begin
        done <= 1'b0;

        if (start && !running) begin
            // Capture the request.  The actual next-key assignment happens on
            // the following clock while running is high.
            running <= 1'b1;
        end else if (running) begin
            // temp is g(W3): RotWord + SubWord + RCON for AES-128.
            temp = {b0, b1, b2, b3} ^ RCON(round);

            // AES-128 key schedule:
            //   W4 = W0 XOR temp
            //   W5 = W1 XOR W4
            //   W6 = W2 XOR W5
            //   W7 = W3 XOR W6
            // The expressions below are expanded directly from those equations.
            out_key[127:96] <= in_key[127:96] ^ temp;
            out_key[95:64]  <= in_key[95:64]  ^ in_key[127:96] ^ temp;
            out_key[63:32]  <= in_key[63:32]  ^ in_key[95:64]  ^ in_key[127:96] ^ temp;
            out_key[31:0]   <= in_key[31:0]   ^ in_key[63:32]  ^ in_key[95:64]  ^ in_key[127:96] ^ temp;

            running <= 1'b0;
            done    <= 1'b1;
        end
    end
end
endmodule
