onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /riscv_core_tb/clk
add wave -noupdate /riscv_core_tb/rst_n
add wave -noupdate /riscv_core_tb/current_pc_debug_tb
add wave -noupdate /riscv_core_tb/aes_done_debug_tb
add wave -noupdate /riscv_core_tb/aes_ciphertext_debug_tb
add wave -noupdate /riscv_core_tb/uart_tx_tb
add wave -noupdate /riscv_core_tb/spi_miso_tb
add wave -noupdate /riscv_core_tb/spi_mosi_tb
add wave -noupdate /riscv_core_tb/spi_sclk_tb
add wave -noupdate /riscv_core_tb/spi_ss_n_tb
add wave -noupdate /riscv_core_tb/irq_debug_tb
add wave -noupdate /riscv_core_tb/sleep_debug_tb
add wave -noupdate /riscv_core_tb/activity_counter_debug_tb
add wave -noupdate /riscv_core_tb/pass_count
add wave -noupdate /riscv_core_tb/fail_count
add wave -noupdate /riscv_core_tb/if_stall_seen_count
add wave -noupdate /riscv_core_tb/if_flush_seen_count
add wave -noupdate /riscv_core_tb/aes_sel_seen_count
add wave -noupdate /riscv_core_tb/aes_write_seen_count
add wave -noupdate /riscv_core_tb/aes_read_seen_count
add wave -noupdate /riscv_core_tb/uart_done_seen_count
add wave -noupdate /riscv_core_tb/irq_seen_count
add wave -noupdate /riscv_core_tb/spi_sclk_toggle_count
add wave -noupdate /riscv_core_tb/spi_sclk_prev
add wave -noupdate /riscv_core_tb/obs_if_pc
add wave -noupdate /riscv_core_tb/obs_if_instr
add wave -noupdate /riscv_core_tb/obs_if_stall
add wave -noupdate /riscv_core_tb/obs_if_flush
add wave -noupdate /riscv_core_tb/obs_id_pc
add wave -noupdate /riscv_core_tb/obs_id_instr
add wave -noupdate /riscv_core_tb/obs_id_rs1
add wave -noupdate /riscv_core_tb/obs_id_rs2
add wave -noupdate /riscv_core_tb/obs_id_rd
add wave -noupdate /riscv_core_tb/obs_id_rs1_data
add wave -noupdate /riscv_core_tb/obs_id_rs2_data
add wave -noupdate /riscv_core_tb/obs_id_imm
add wave -noupdate /riscv_core_tb/obs_id_reg_write
add wave -noupdate /riscv_core_tb/obs_id_mem_read
add wave -noupdate /riscv_core_tb/obs_id_mem_write
add wave -noupdate /riscv_core_tb/obs_id_mem_to_reg
add wave -noupdate /riscv_core_tb/obs_id_alu_src
add wave -noupdate /riscv_core_tb/obs_id_branch
add wave -noupdate /riscv_core_tb/obs_id_alu_ctrl
add wave -noupdate /riscv_core_tb/obs_ex_pc
add wave -noupdate /riscv_core_tb/obs_ex_rs1
add wave -noupdate /riscv_core_tb/obs_ex_rs2
add wave -noupdate /riscv_core_tb/obs_ex_rd
add wave -noupdate /riscv_core_tb/obs_ex_rs1_data
add wave -noupdate /riscv_core_tb/obs_ex_rs2_data
add wave -noupdate /riscv_core_tb/obs_ex_imm
add wave -noupdate /riscv_core_tb/obs_ex_reg_write
add wave -noupdate /riscv_core_tb/obs_ex_mem_read
add wave -noupdate /riscv_core_tb/obs_ex_mem_write
add wave -noupdate /riscv_core_tb/obs_ex_mem_to_reg
add wave -noupdate /riscv_core_tb/obs_ex_alu_src
add wave -noupdate /riscv_core_tb/obs_ex_branch
add wave -noupdate /riscv_core_tb/obs_ex_alu_ctrl
add wave -noupdate /riscv_core_tb/obs_forward_a
add wave -noupdate /riscv_core_tb/obs_forward_b
add wave -noupdate /riscv_core_tb/obs_ex_op_a
add wave -noupdate /riscv_core_tb/obs_ex_op_b
add wave -noupdate /riscv_core_tb/obs_ex_alu_result_raw
add wave -noupdate /riscv_core_tb/obs_ex_alu_result
add wave -noupdate /riscv_core_tb/obs_ex_rs2_forwarded
add wave -noupdate /riscv_core_tb/obs_ex_branch_target
add wave -noupdate /riscv_core_tb/obs_ex_branch_taken
add wave -noupdate /riscv_core_tb/obs_mem_alu_result
add wave -noupdate /riscv_core_tb/obs_mem_write_data
add wave -noupdate /riscv_core_tb/obs_mem_rd
add wave -noupdate /riscv_core_tb/obs_mem_reg_write
add wave -noupdate /riscv_core_tb/obs_mem_read
add wave -noupdate /riscv_core_tb/obs_mem_write
add wave -noupdate /riscv_core_tb/obs_mem_to_reg
add wave -noupdate /riscv_core_tb/obs_mem_eff_addr
add wave -noupdate /riscv_core_tb/obs_mem_ls_tag
add wave -noupdate /riscv_core_tb/obs_mem_raw_word
add wave -noupdate /riscv_core_tb/obs_mem_merged_store
add wave -noupdate /riscv_core_tb/obs_mem_read_data
add wave -noupdate /riscv_core_tb/obs_wb_alu_result
add wave -noupdate /riscv_core_tb/obs_wb_mem_read_data
add wave -noupdate /riscv_core_tb/obs_wb_rd
add wave -noupdate /riscv_core_tb/obs_wb_reg_write
add wave -noupdate /riscv_core_tb/obs_wb_mem_to_reg
add wave -noupdate /riscv_core_tb/obs_wb_data
add wave -noupdate /riscv_core_tb/obs_x0
add wave -noupdate /riscv_core_tb/obs_x1
add wave -noupdate /riscv_core_tb/obs_x2
add wave -noupdate /riscv_core_tb/obs_x3
add wave -noupdate /riscv_core_tb/obs_x4
add wave -noupdate /riscv_core_tb/obs_x5
add wave -noupdate /riscv_core_tb/obs_x6
add wave -noupdate /riscv_core_tb/obs_x7
add wave -noupdate /riscv_core_tb/obs_x8
add wave -noupdate /riscv_core_tb/obs_x9
add wave -noupdate /riscv_core_tb/obs_x10
add wave -noupdate /riscv_core_tb/obs_x11
add wave -noupdate /riscv_core_tb/obs_x12
add wave -noupdate /riscv_core_tb/obs_x13
add wave -noupdate /riscv_core_tb/obs_x14
add wave -noupdate /riscv_core_tb/obs_x15
add wave -noupdate /riscv_core_tb/obs_x16
add wave -noupdate /riscv_core_tb/obs_x17
add wave -noupdate /riscv_core_tb/obs_x18
add wave -noupdate /riscv_core_tb/obs_x19
add wave -noupdate /riscv_core_tb/obs_x20
add wave -noupdate /riscv_core_tb/obs_x21
add wave -noupdate /riscv_core_tb/obs_x22
add wave -noupdate /riscv_core_tb/obs_x23
add wave -noupdate /riscv_core_tb/obs_x24
add wave -noupdate /riscv_core_tb/obs_x25
add wave -noupdate /riscv_core_tb/obs_x26
add wave -noupdate /riscv_core_tb/obs_x27
add wave -noupdate /riscv_core_tb/obs_x28
add wave -noupdate /riscv_core_tb/obs_x29
add wave -noupdate /riscv_core_tb/obs_x30
add wave -noupdate /riscv_core_tb/obs_x31
add wave -noupdate /riscv_core_tb/obs_dmem0
add wave -noupdate /riscv_core_tb/obs_dmem1
add wave -noupdate /riscv_core_tb/obs_dmem2
add wave -noupdate /riscv_core_tb/obs_dmem3
add wave -noupdate /riscv_core_tb/obs_dmem4
add wave -noupdate /riscv_core_tb/obs_dmem5
add wave -noupdate /riscv_core_tb/obs_dmem6
add wave -noupdate /riscv_core_tb/obs_dmem7
add wave -noupdate /riscv_core_tb/obs_aes_sel
add wave -noupdate /riscv_core_tb/obs_aes_write_en
add wave -noupdate /riscv_core_tb/obs_aes_read_en
add wave -noupdate /riscv_core_tb/obs_aes_reg_offset
add wave -noupdate /riscv_core_tb/obs_aes_start
add wave -noupdate /riscv_core_tb/obs_aes_busy
add wave -noupdate /riscv_core_tb/obs_aes_done
add wave -noupdate /riscv_core_tb/obs_aes_key
add wave -noupdate /riscv_core_tb/obs_aes_plaintext
add wave -noupdate /riscv_core_tb/obs_aes_ciphertext
add wave -noupdate /riscv_core_tb/obs_aes_round
add wave -noupdate /riscv_core_tb/obs_aes_state
add wave -noupdate /riscv_core_tb/obs_aes_round_key
add wave -noupdate /riscv_core_tb/obs_uart_busy
add wave -noupdate /riscv_core_tb/obs_uart_done
add wave -noupdate /riscv_core_tb/obs_irq
add wave -noupdate /riscv_core_tb/obs_sleep
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {15364882 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 345
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1475785 ps} {3725036 ps}
